(function exposeStudentBenefits(global) {
    'use strict';

    const verifiedOn = '2026-08-16';

    const rawBenefits = [
        {
            id: 'github',
            name: 'GitHub Student Developer Pack',
            category: 'development',
            secondaryCategories: ['education'],
            benefitType: 'free_student',
            benefitLabel: 'Gratuito para estudante verificado',
            availability: 'Disponível internacionalmente',
            targetAudience: 'Estudantes elegíveis e verificados pelo GitHub Education',
            verification: 'Verificação acadêmica pelo GitHub Education',
            eligibility: 'É necessário comprovar vínculo estudantil conforme os critérios do GitHub Education.',
            description: 'Pacote educacional com recursos do GitHub e ofertas de ferramentas parceiras para aprender e desenvolver projetos.',
            tags: ['GitHub Education', 'ferramentas de desenvolvimento', 'parceiros'],
            officialUrl: 'https://education.github.com/pack',
            lastVerified: verifiedOn,
            status: 'verified',
            icon: 'github'
        },
        {
            id: 'github-copilot',
            name: 'GitHub Copilot Student',
            category: 'development',
            secondaryCategories: [],
            benefitType: 'free_student',
            benefitLabel: 'Copilot gratuito para estudantes verificados',
            availability: 'Disponível internacionalmente',
            targetAudience: 'Estudantes verificados no GitHub Education',
            verification: 'Conta estudantil aprovada no GitHub Education',
            eligibility: 'A elegibilidade estudantil é reavaliada periodicamente pelo GitHub.',
            description: 'Assistente de IA para programação com sugestões de código e recursos do Copilot em contas estudantis elegíveis.',
            tags: ['Copilot', 'IA para programação', 'completions'],
            officialUrl: 'https://docs.github.com/pt/copilot/how-tos/copilot-on-github/set-up-copilot/enable-copilot/set-up-for-students',
            lastVerified: verifiedOn,
            status: 'verified',
            icon: 'sparkles'
        },
        {
            id: 'jetbrains',
            name: 'JetBrains Student Pack',
            category: 'development',
            secondaryCategories: [],
            benefitType: 'free_student',
            benefitLabel: 'Licenças educacionais gratuitas',
            availability: 'Disponível internacionalmente',
            targetAudience: 'Estudantes e docentes elegíveis',
            verification: 'Comprovação acadêmica; renovação enquanto houver elegibilidade',
            eligibility: 'As licenças são destinadas a estudo e uso educacional, conforme os termos da JetBrains.',
            description: 'Acesso educacional às IDEs profissionais da JetBrains para estudos e projetos acadêmicos.',
            tags: ['IntelliJ IDEA', 'PyCharm', 'WebStorm'],
            officialUrl: 'https://www.jetbrains.com/community/education/#students',
            lastVerified: verifiedOn,
            status: 'verified',
            logo: '../img-interno/jetbrains-logo.png'
        },
        {
            id: 'notion',
            name: 'Notion Education Plus',
            category: 'productivity-studies',
            secondaryCategories: ['education'],
            benefitType: 'free_student',
            benefitLabel: 'Plano Plus gratuito para estudante elegível',
            availability: 'Disponível para instituições reconhecidas',
            targetAudience: 'Estudantes universitários e docentes elegíveis',
            verification: 'Cadastro individual com e-mail acadêmico aceito',
            eligibility: 'O benefício depende de instituição reconhecida e de e-mail acadêmico elegível; não se aplica a espaços de trabalho com vários membros.',
            description: 'Espaço para organizar notas, disciplinas, projetos e rotinas acadêmicas com recursos do plano Plus.',
            tags: ['notas', 'organização', 'projetos'],
            officialUrl: 'https://www.notion.com/help/notion-for-education',
            lastVerified: verifiedOn,
            status: 'verified',
            logo: '../img-interno/notion_logo.png'
        },
        {
            id: 'figma',
            name: 'Figma for Education',
            category: 'design-creativity',
            secondaryCategories: ['education'],
            benefitType: 'free_student',
            benefitLabel: 'Professional Plan gratuito',
            availability: 'Disponível para ensino superior elegível',
            targetAudience: 'Estudantes e docentes do ensino superior elegíveis',
            verification: 'E-mail acadêmico e verificação de elegibilidade',
            eligibility: 'A aprovação depende dos critérios educacionais e da instituição informada à Figma.',
            description: 'Recursos profissionais de design e colaboração para trabalhos, interfaces e protótipos acadêmicos.',
            tags: ['Figma', 'FigJam', 'prototipação'],
            officialUrl: 'https://www.figma.com/education/higher-education/',
            lastVerified: verifiedOn,
            status: 'verified',
            logo: '../img-interno/figma_logo_6.png'
        },
        {
            id: 'miro',
            name: 'Miro Education',
            category: 'productivity-studies',
            secondaryCategories: ['design-creativity', 'education'],
            benefitType: 'free_student',
            benefitLabel: 'Education Plan gratuito',
            availability: 'Disponível para instituições credenciadas',
            targetAudience: 'Estudantes e profissionais de instituições educacionais elegíveis',
            verification: 'E-mail acadêmico ou documento comprobatório',
            eligibility: 'A Miro analisa a instituição e a documentação acadêmica para conceder o plano Education.',
            description: 'Quadros colaborativos para brainstorming, mapas, planejamento e trabalhos em grupo.',
            tags: ['whiteboards', 'colaboração', 'brainstorming'],
            officialUrl: 'https://miro.com/education/',
            lastVerified: verifiedOn,
            status: 'verified',
            icon: 'panels-top-left'
        },
        {
            id: 'azure',
            name: 'Azure for Students',
            category: 'cloud-data',
            secondaryCategories: ['education'],
            benefitType: 'free_student',
            benefitLabel: 'US$ 100 em créditos · sem cartão',
            availability: 'Oferta estudantil em mercados elegíveis',
            targetAudience: 'Estudantes universitários em tempo integral elegíveis',
            verification: 'Verificação acadêmica pela Microsoft',
            eligibility: 'O crédito é válido por 12 meses; a renovação depende da manutenção da elegibilidade estudantil.',
            description: 'Créditos e serviços de nuvem para experimentar recursos de cloud, IA e desenvolvimento sem cadastrar cartão.',
            tags: ['cloud', 'IA', 'desenvolvimento'],
            officialUrl: 'https://azure.microsoft.com/pt-br/free/students',
            lastVerified: verifiedOn,
            status: 'verified',
            logo: '../img-interno/azure-logo.png',
            volatileFields: ['benefitLabel']
        },
        {
            id: 'aws',
            name: 'AWS Educate',
            category: 'cloud-data',
            secondaryCategories: ['education'],
            benefitType: 'free_for_all',
            benefitLabel: 'Treinamentos e labs gratuitos · sem cartão',
            availability: 'Disponível internacionalmente',
            targetAudience: 'Pessoas a partir de 13 anos interessadas em cloud',
            verification: 'Cadastro na AWS Educate; labs sem cartão de crédito',
            eligibility: 'O acesso descrito é ao catálogo educacional, aos laboratórios e badges — não representa crédito geral de US$ 100.',
            description: 'Programa gratuito para desenvolver habilidades em nuvem com treinamento, laboratórios práticos e badges.',
            tags: ['training', 'labs', 'badges'],
            officialUrl: 'https://aws.amazon.com/education/awseducate/',
            lastVerified: verifiedOn,
            status: 'verified',
            logo: '../img-interno/aws_logo_9.png'
        },
        {
            id: 'autodesk',
            name: 'Autodesk Education',
            category: 'design-creativity',
            secondaryCategories: ['education'],
            benefitType: 'free_student',
            benefitLabel: '1 ano gratuito, renovável enquanto elegível',
            availability: 'Disponível internacionalmente',
            targetAudience: 'Estudantes e docentes elegíveis',
            verification: 'Comprovação de vínculo com instituição qualificada',
            eligibility: 'A licença é apenas para fins educacionais, não comerciais, e precisa ser renovada enquanto houver elegibilidade.',
            description: 'Acesso educacional a softwares Autodesk para projetos de design, arquitetura e engenharia.',
            tags: ['AutoCAD', 'Revit', 'Fusion'],
            officialUrl: 'https://www.autodesk.com/education/edu-software/overview',
            lastVerified: verifiedOn,
            status: 'verified',
            icon: 'drafting-compass'
        },
        {
            id: 'microsoft365',
            name: 'Microsoft 365 Education',
            category: 'productivity-studies',
            secondaryCategories: ['education'],
            benefitType: 'institution_dependent',
            benefitLabel: 'Gratuito quando instituição e e-mail são elegíveis',
            availability: 'Depende da participação da instituição',
            targetAudience: 'Estudantes e docentes de instituições elegíveis',
            verification: 'E-mail acadêmico válido de instituição qualificada',
            eligibility: 'O acesso não é universal: os aplicativos e recursos disponíveis dependem do plano educacional da instituição.',
            description: 'Ferramentas Microsoft para documentos, planilhas e apresentações quando a instituição participa do programa Education.',
            tags: ['Word', 'Excel', 'PowerPoint'],
            officialUrl: 'https://www.microsoft.com/pt-br/education/products/office-365-education',
            lastVerified: verifiedOn,
            status: 'institution_dependent',
            icon: 'layout-grid'
        },
        {
            id: 'mongodb',
            name: 'MongoDB for Students',
            category: 'development',
            secondaryCategories: ['education'],
            benefitType: 'student_program',
            benefitLabel: 'Benefícios via GitHub Student Developer Pack',
            availability: 'Disponível para participantes elegíveis do GitHub Pack',
            targetAudience: 'Estudantes verificados no GitHub Student Developer Pack',
            verification: 'GitHub Student Developer Pack e conta MongoDB',
            eligibility: 'A certificação gratuita exige verificação e conclusão dos requisitos de aprendizagem publicados pela MongoDB.',
            description: 'Programa estudantil com recursos para aprender MongoDB, praticar com Atlas e buscar certificação conforme os requisitos oficiais.',
            tags: ['MongoDB', 'database', 'certificação'],
            officialUrl: 'https://www.mongodb.com/students',
            lastVerified: verifiedOn,
            status: 'verified',
            logo: '../img-interno/mongodb_logo_8.png'
        },
        {
            id: 'adobe',
            name: 'Adobe Creative Cloud para estudantes',
            category: 'design-creativity',
            secondaryCategories: [],
            benefitType: 'student_discount',
            benefitLabel: 'Aprox. 74% OFF · R$ 55/mês no 1º ano',
            availability: 'Oferta verificada no Brasil',
            targetAudience: 'Estudantes e docentes elegíveis',
            verification: 'Comprovação de elegibilidade educacional',
            eligibility: 'O preço promocional vale para a oferta e o período divulgados; o valor posterior e as condições podem mudar.',
            description: 'Plano com aplicativos criativos da Adobe oferecido com preço educacional temporário.',
            tags: ['Photoshop', 'Illustrator', 'Creative Cloud'],
            officialUrl: 'https://www.adobe.com/br/creativecloud/buy/students/desperte-sua-criatividade-com-melhores-apps.html',
            lastVerified: verifiedOn,
            status: 'verified',
            logo: '../img-interno/adobe_logo.png',
            volatileFields: ['benefitLabel']
        },
        {
            id: 'spotify',
            name: 'Spotify Premium Universitário',
            category: 'entertainment',
            secondaryCategories: [],
            benefitType: 'student_discount',
            benefitLabel: 'R$ 12,90/mês',
            availability: 'Disponível no Brasil',
            targetAudience: 'Universitários elegíveis com 18 anos ou mais',
            verification: 'Verificação acadêmica pela SheerID, renovada periodicamente',
            eligibility: 'A instituição precisa ser elegível e a condição de estudante deve ser confirmada novamente conforme as regras do plano.',
            description: 'Assinatura individual do Spotify Premium com preço universitário para estudantes verificados.',
            tags: ['música', 'streaming', 'SheerID'],
            officialUrl: 'https://www.spotify.com/br-pt/student/',
            lastVerified: verifiedOn,
            status: 'verified',
            logo: '../img-interno/spotify-logo.png',
            volatileFields: ['benefitLabel']
        },
        {
            id: 'apple-music',
            name: 'Apple Music Universitário',
            category: 'entertainment',
            secondaryCategories: [],
            benefitType: 'student_discount',
            benefitLabel: 'R$ 12,90/mês · inclui Apple TV',
            availability: 'Disponível no Brasil',
            targetAudience: 'Universitários elegíveis e verificados',
            verification: 'Comprovação periódica da condição de estudante',
            eligibility: 'O preço, a inclusão do Apple TV e as condições seguem a oferta universitária vigente da Apple.',
            description: 'Plano individual de música com preço universitário e acesso ao Apple TV conforme a oferta atual.',
            tags: ['Apple Music', 'Apple TV', 'streaming'],
            officialUrl: 'https://www.apple.com/br/apple-music/',
            lastVerified: verifiedOn,
            status: 'verified',
            icon: 'music-2',
            volatileFields: ['benefitLabel']
        },
        {
            id: 'youtube-premium',
            name: 'YouTube Premium Student',
            category: 'entertainment',
            secondaryCategories: [],
            benefitType: 'student_discount',
            benefitLabel: 'Plano universitário com desconto',
            availability: 'Disponível no Brasil',
            targetAudience: 'Universitários de instituições aprovadas pela SheerID',
            verification: 'Verificação anual da condição de estudante pela SheerID',
            eligibility: 'A instituição deve ser aprovada pela SheerID; o benefício pode ser mantido pelo período máximo definido nas regras oficiais.',
            description: 'Plano YouTube Premium com desconto para universitários verificados, sem fixar um preço que possa mudar.',
            tags: ['YouTube Premium', 'vídeos', 'SheerID'],
            officialUrl: 'https://support.google.com/youtube/answer/9158808?hl=pt-BR',
            lastVerified: verifiedOn,
            status: 'verified',
            icon: 'youtube'
        },
        {
            id: 'samsung-students',
            name: 'Samsung Estudantes',
            category: 'technology',
            secondaryCategories: [],
            benefitType: 'student_discount',
            benefitLabel: 'Até 30% OFF em produtos selecionados',
            availability: 'Disponível no Brasil',
            targetAudience: 'Estudantes entre 18 e 26 anos que atendam aos critérios da oferta',
            verification: 'E-mail acadêmico elegível ou validação pela UNiDAYS',
            eligibility: 'O percentual varia por produto, campanha e disponibilidade; consulte o portal estudantil antes da compra.',
            description: 'Loja estudantil com descontos variáveis em produtos Samsung selecionados.',
            tags: ['smartphones', 'tablets', 'notebooks'],
            officialUrl: 'https://www.samsung.com/br/students-offers/',
            lastVerified: verifiedOn,
            status: 'verified',
            icon: 'smartphone',
            volatileFields: ['benefitLabel']
        },
        {
            id: 'apple-education',
            name: 'Apple Store para Educação',
            category: 'technology',
            secondaryCategories: ['education'],
            benefitType: 'education_price',
            benefitLabel: 'Preços educacionais em produtos elegíveis',
            availability: 'Disponível no Brasil',
            targetAudience: 'Universitários, pessoas aceitas no ensino superior e profissionais da educação elegíveis',
            verification: 'Elegibilidade educacional conforme as condições da Apple',
            eligibility: 'Produtos, limites de compra e preços educacionais podem mudar; confira a loja oficial no momento da compra.',
            description: 'Loja oficial com preços especiais de educação para Mac, iPad e produtos elegíveis.',
            tags: ['Mac', 'iPad', 'preço educacional'],
            officialUrl: 'https://www.apple.com/br-edu/store',
            lastVerified: verifiedOn,
            status: 'verified',
            icon: 'laptop',
            volatileFields: ['benefitLabel']
        },
        {
            id: '1password-student',
            name: '1Password para estudantes',
            category: 'development',
            secondaryCategories: ['productivity-studies'],
            benefitType: 'free_student',
            benefitLabel: '1 ano gratuito via GitHub Student Pack',
            availability: 'Disponível internacionalmente',
            targetAudience: 'Estudantes do ensino superior verificados pelo GitHub Education',
            verification: 'GitHub Student Developer Pack ativo',
            eligibility: 'A oferta individual pode ser resgatada uma vez; após o período gratuito, a continuidade depende das condições vigentes da 1Password.',
            description: 'Gerenciador de senhas e ferramentas para proteger contas, credenciais e segredos usados em projetos de desenvolvimento.',
            tags: ['senhas', 'segurança', 'Developer Tools'],
            officialUrl: 'https://1password.com/developers/students',
            lastVerified: verifiedOn,
            status: 'verified',
            icon: 'key-round',
            volatileFields: ['benefitLabel']
        },
        {
            id: 'frontend-masters',
            name: 'Frontend Masters Student',
            category: 'education',
            secondaryCategories: ['development'],
            benefitType: 'free_student',
            benefitLabel: '6 meses gratuitos via GitHub Student Pack',
            availability: 'Disponível internacionalmente',
            targetAudience: 'Estudantes verificados no GitHub Student Developer Pack',
            verification: 'GitHub Student Developer Pack ativo',
            eligibility: 'O acesso gratuito dura seis meses e não exige cartão; a continuidade posterior segue os planos vigentes da plataforma.',
            description: 'Acesso temporário à biblioteca de cursos e trilhas de desenvolvimento front-end da plataforma.',
            tags: ['cursos', 'front-end', 'GitHub Student Pack'],
            officialUrl: 'https://frontendmasters.com/welcome/github-student-developers/',
            lastVerified: verifiedOn,
            status: 'verified',
            icon: 'panels-top-left',
            volatileFields: ['benefitLabel']
        },
        {
            id: 'meia-entrada', name: 'Meia-entrada estudantil', category: 'rights-mobility', secondaryCategories: [], subcategory: 'rights',
            benefitType: 'government_benefit', benefitLabel: '50% do valor do ingresso nos eventos abrangidos',
            availability: 'Brasil', targetAudience: 'Estudantes regularmente matriculados que atendam às regras legais',
            verification: 'Carteira de Identificação Estudantil válida e documentação exigida', accessMethod: 'government_eligibility', sourceChannel: 'government',
            eligibility: 'A Lei nº 12.933/2013 define eventos abrangidos, comprovação e limites; o benefício não é cumulativo com promoções e não cobre serviços adicionais.',
            description: 'Direito previsto em lei para acesso a determinados eventos artístico-culturais, esportivos e de entretenimento.',
            tags: ['meia entrada', 'cinema', 'eventos', 'direito estudantil'], officialUrl: 'https://www.planalto.gov.br/ccivil_03/_ato2011-2014/2013/lei/l12933.htm',
            lastVerified: verifiedOn, status: 'verified', icon: 'ticket-percent'
        },
        {
            id: 'cartao-transcol-escolar', name: 'Cartão Transcol Escolar', category: 'rights-mobility', secondaryCategories: [], subcategory: 'mobility',
            benefitType: 'regional_benefit', benefitLabel: '50% de desconto na tarifa do Transcol',
            availability: 'Espírito Santo · Sistema Transcol', regionalLabel: 'Espírito Santo', targetAudience: 'Estudantes de instituições reconhecidas e cadastradas no GVBus',
            verification: 'Cadastro ou recadastro estudantil e validação pela instituição de ensino', accessMethod: 'student_verification', sourceChannel: 'direct',
            eligibility: 'É um benefício regional. A instituição deve ser reconhecida e cadastrada; o estudante precisa seguir o procedimento e apresentar os documentos solicitados pelo GVBus.',
            description: 'Cartão escolar que concede meia tarifa estudantil nos deslocamentos atendidos pelo Sistema Transcol.',
            tags: ['ônibus', 'Transcol', 'Grande Vitória', 'meia tarifa'], officialUrl: 'https://gvbus.org.br/va-de-transcol/estudante/',
            lastVerified: verifiedOn, status: 'verified', icon: 'bus-front'
        },
        {
            id: 'id-jovem', name: 'ID Jovem', category: 'rights-mobility', secondaryCategories: [], subcategory: 'rights',
            benefitType: 'government_benefit', benefitLabel: 'Transporte interestadual e meia-entrada para jovens elegíveis',
            availability: 'Brasil', targetAudience: 'Jovens de baixa renda entre 15 e 29 anos que atendam aos critérios do programa',
            verification: 'CPF ou NIS e Cadastro Único atualizado', accessMethod: 'government_eligibility', sourceChannel: 'government',
            eligibility: 'Não é exclusivo para estudantes. Exige renda familiar de até dois salários mínimos e inscrição atualizada no CadÚnico, conforme as regras governamentais.',
            description: 'Documento digital gratuito que dá acesso a benefícios culturais e a vagas gratuitas ou com desconto no transporte interestadual.',
            tags: ['ID Jovem', 'CadÚnico', 'viagem', 'meia entrada'], officialUrl: 'https://www.gov.br/pt-br/servicos/obter-a-carteira-de-identidade-jovem',
            lastVerified: verifiedOn, status: 'verified', icon: 'badge-id-card'
        },
        {
            id: 'unidays-brasil', name: 'UNiDAYS Brasil', category: 'shopping-benefits', secondaryCategories: [], subcategory: 'benefits-hub',
            benefitType: 'student_program', benefitLabel: 'Acesso gratuito a descontos variáveis de marcas parceiras',
            availability: 'Brasil', targetAudience: 'Estudantes cuja instituição ou documentação seja aceita pela UNiDAYS',
            verification: 'E-mail institucional, portal acadêmico ou documento estudantil aceito', accessMethod: 'student_verification', sourceChannel: 'unidays',
            eligibility: 'A adesão à plataforma é gratuita, mas marcas, percentuais, produtos e duração das ofertas mudam ao longo do tempo.',
            description: 'Hub de verificação estudantil que reúne descontos e condições especiais de diferentes marcas.',
            tags: ['compras', 'descontos', 'marcas', 'verificação estudantil'], officialUrl: 'https://www.myunidays.com/BR/pt-BR',
            lastVerified: verifiedOn, status: 'verified', fallbackLabel: 'U', volatileFields: ['benefitLabel']
        },
        {
            id: 'isic', name: 'ISIC · Carteira Mundial do Estudante', category: 'shopping-benefits', secondaryCategories: ['rights-mobility'], subcategory: 'travel',
            benefitType: 'student_discount', benefitLabel: 'Rede internacional de vantagens e descontos',
            availability: 'Brasil e rede internacional participante', targetAudience: 'Estudantes elegíveis para emissão da carteira ISIC',
            verification: 'Comprovação estudantil no processo de emissão', accessMethod: 'student_verification', sourceChannel: 'isic',
            eligibility: 'A emissão da carteira pode ser paga. Benefícios, estabelecimentos e condições variam por país, local e período.',
            description: 'Carteira internacional de identificação estudantil conectada a uma rede de vantagens em viagens, cultura, serviços e compras.',
            tags: ['viagens', 'carteira estudantil', 'descontos internacionais'], officialUrl: 'https://www.isic.org/cards/isic/',
            lastVerified: verifiedOn, status: 'verified', fallbackLabel: 'ISIC', volatileFields: ['benefitLabel']
        },
        {
            id: 'lenovo-students', name: 'Lenovo Estudantes', category: 'technology', secondaryCategories: ['shopping-benefits'], subcategory: 'hardware',
            benefitType: 'education_price', benefitLabel: 'Preços e descontos educacionais em produtos selecionados',
            availability: 'Brasil', targetAudience: 'Estudantes elegíveis no programa educacional Lenovo',
            verification: 'Solicitação e validação do status acadêmico', accessMethod: 'education_store', sourceChannel: 'direct',
            eligibility: 'Produtos, descontos e códigos disponíveis variam. A validação é necessária antes de acessar as condições educacionais.',
            description: 'Programa brasileiro de compra educacional para notebooks, desktops e acessórios elegíveis.',
            tags: ['notebook', 'computador', 'hardware', 'Lenovo Edu'], officialUrl: 'https://www.lenovo.com/br/pt/estudantes/',
            lastVerified: verifiedOn, status: 'verified', volatileFields: ['benefitLabel']
        },
        {
            id: 'dell-students', name: 'Dell para Estudantes', category: 'technology', secondaryCategories: ['shopping-benefits'], subcategory: 'hardware',
            benefitType: 'student_discount', benefitLabel: 'Cupom estudantil para produtos elegíveis',
            availability: 'Brasil', targetAudience: 'Universitários, estudantes técnicos e outros perfis acadêmicos aceitos pela Dell',
            verification: 'Validação do status de estudante antes da emissão do cupom', accessMethod: 'student_verification', sourceChannel: 'direct',
            eligibility: 'O cupom se aplica somente a produtos elegíveis no Dell.com.br e possui exclusões e limites definidos pela oferta vigente.',
            description: 'Programa de benefícios para compra de notebooks, desktops e acessórios selecionados no site brasileiro da Dell.',
            tags: ['notebook', 'desktop', 'acessórios', 'cupom'], officialUrl: 'https://www.dell.com/pt-br/lp/students',
            lastVerified: verifiedOn, status: 'verified', volatileFields: ['benefitLabel']
        },
        {
            id: 'microsoft-store-education', name: 'Microsoft Store Educação', category: 'technology', secondaryCategories: ['shopping-benefits'], subcategory: 'hardware',
            benefitType: 'education_price', benefitLabel: 'Desconto educacional em dispositivos selecionados',
            availability: 'Brasil · produtos participantes', targetAudience: 'Estudantes, pais ou responsáveis e educadores elegíveis',
            verification: 'Conta Microsoft e confirmação de elegibilidade', accessMethod: 'education_store', sourceChannel: 'direct',
            eligibility: 'O desconto se aplica somente a dispositivos e produtos participantes; disponibilidade e condições podem mudar.',
            description: 'Condições educacionais para dispositivos selecionados, incluindo produtos Surface quando disponíveis.',
            tags: ['Surface', 'notebook', 'dispositivos', 'Microsoft Store'], officialUrl: 'https://www.microsoft.com/pt-br/education/students',
            lastVerified: verifiedOn, status: 'verified', volatileFields: ['benefitLabel']
        },
        {
            id: 'tableau-students', name: 'Tableau for Students', category: 'cloud-data', secondaryCategories: ['education'], subcategory: 'data',
            benefitType: 'free_for_all', benefitLabel: 'Tableau Desktop Public Edition gratuito para aprender',
            availability: 'Disponível internacionalmente', targetAudience: 'Estudantes e demais pessoas aprendendo visualização de dados',
            verification: 'Cadastro no Tableau Public', accessMethod: 'direct', sourceChannel: 'direct',
            eligibility: 'A edição pública é gratuita e não exige renovação, mas não pode ser usada comercialmente e publica trabalhos no Tableau Public.',
            description: 'Software e recursos acadêmicos para desenvolver habilidades em visualização e análise de dados.',
            tags: ['dados', 'visualização', 'analytics', 'dashboards'], officialUrl: 'https://www.tableau.com/pt-br/academic/students',
            lastVerified: verifiedOn, status: 'verified'
        },
        {
            id: 'unity-student', name: 'Unity Student', category: 'development', secondaryCategories: ['design-creativity'], subcategory: 'games',
            benefitType: 'free_student', benefitLabel: 'Plano estudantil gratuito, renovável enquanto elegível',
            availability: 'Disponível em regiões atendidas pela verificação', targetAudience: 'Estudantes com 16 anos ou mais em instituição educacional credenciada',
            verification: 'Verificação acadêmica pela SheerID', accessMethod: 'sheerid', sourceChannel: 'direct',
            eligibility: 'A licença individual vale por um ano e pode ser renovada durante o vínculo acadêmico, segundo as condições do Unity Student Plan.',
            description: 'Acesso estudantil ao Unity Pro Editor e a recursos para criação de jogos e experiências interativas.',
            tags: ['games', 'Unity', '3D', 'desenvolvimento'], officialUrl: 'https://unity.com/products/unity-student',
            lastVerified: verifiedOn, status: 'verified', volatileFields: ['benefitLabel']
        },
        {
            id: 'gitkraken-student', name: 'GitKraken Student', category: 'development', secondaryCategories: [], subcategory: 'developer-tools',
            benefitType: 'free_student', benefitLabel: '6 meses gratuitos; preço estudantil depois',
            availability: 'Disponível internacionalmente', targetAudience: 'Estudantes verificados no GitHub Student Developer Pack',
            verification: 'GitHub Student Developer Pack ativo e conta GitKraken conectada', accessMethod: 'github_education', sourceChannel: 'github_student_pack',
            eligibility: 'A gratuidade inicial tem duração limitada; depois, a continuidade usa o preço estudantil vigente enquanto houver verificação.',
            description: 'Ferramentas Git para desktop, editor, linha de comando e organização do fluxo de desenvolvimento.',
            tags: ['Git', 'GitLens', 'GitHub', 'desenvolvimento'], officialUrl: 'https://www.gitkraken.com/github-student-developer-pack-bundle',
            lastVerified: verifiedOn, status: 'verified', volatileFields: ['benefitLabel']
        },
        {
            id: 'datacamp-student', name: 'DataCamp via GitHub Student Pack', category: 'education', secondaryCategories: ['cloud-data'], subcategory: 'data',
            benefitType: 'free_student', benefitLabel: '3 meses de acesso gratuito',
            availability: 'Disponível por meio do GitHub Student Developer Pack', targetAudience: 'Estudantes verificados no GitHub Education',
            verification: 'GitHub Student Developer Pack e conta DataCamp', accessMethod: 'github_education', sourceChannel: 'github_student_pack',
            eligibility: 'A duração e o escopo seguem a oferta publicada no GitHub Student Developer Pack e podem ser alterados pelo parceiro.',
            description: 'Cursos e trilhas para aprender análise de dados, ciência de dados e programação aplicada.',
            tags: ['dados', 'Python', 'SQL', 'cursos'], officialUrl: 'https://education.github.com/pack',
            lastVerified: verifiedOn, status: 'verified', volatileFields: ['benefitLabel']
        },
        {
            id: 'heroku-student', name: 'Heroku via GitHub Student Pack', category: 'cloud-data', secondaryCategories: ['development'], subcategory: 'cloud',
            benefitType: 'student_program', benefitLabel: 'US$ 13/mês em créditos por 24 meses',
            availability: 'Disponível por meio do GitHub Student Developer Pack', targetAudience: 'Estudantes verificados no GitHub Education',
            verification: 'Resgate pelo GitHub Student Developer Pack', accessMethod: 'github_education', sourceChannel: 'github_student_pack',
            eligibility: 'Crédito, duração, serviços elegíveis e cobrança excedente seguem as condições atuais publicadas no Pack e na Heroku.',
            description: 'Créditos educacionais para publicar, executar e administrar aplicações na plataforma Heroku.',
            tags: ['cloud', 'deploy', 'apps', 'desenvolvimento'], officialUrl: 'https://education.github.com/pack',
            lastVerified: verifiedOn, status: 'verified', volatileFields: ['benefitLabel']
        },
        {
            id: 'ableton-education', name: 'Ableton Education', category: 'design-creativity', secondaryCategories: ['education'], subcategory: 'audio',
            benefitType: 'education_price', benefitLabel: 'Preço educacional para licenças elegíveis',
            availability: 'Disponível em mercados atendidos pela Ableton', targetAudience: 'Estudantes e docentes que atendam à carga acadêmica exigida',
            verification: 'Documento acadêmico enviado após a compra', accessMethod: 'student_verification', sourceChannel: 'direct',
            eligibility: 'Exige vínculo de estudo ou docência dentro dos critérios da Ableton. O desconto não se aplica a todos os produtos ou upgrades.',
            description: 'Licença educacional do Ableton Live para produção musical, gravação e criação de áudio.',
            tags: ['áudio', 'produção musical', 'Ableton Live'], officialUrl: 'https://help.ableton.com/hc/en-us/articles/207333230-EDU-License-FAQ',
            lastVerified: verifiedOn, status: 'verified', volatileFields: ['benefitLabel']
        },
        {
            id: 'matlab-student', name: 'MATLAB and Simulink Student Suite', category: 'cloud-data', secondaryCategories: ['education'], subcategory: 'engineering',
            benefitType: 'education_price', benefitLabel: 'Licença própria para uso estudantil',
            availability: 'Disponibilidade e preço variam por região', targetAudience: 'Estudantes usando o software em cursos de instituições que concedem diploma',
            verification: 'Compra estudantil ou acesso acadêmico fornecido por instituição participante', accessMethod: 'student_verification', sourceChannel: 'direct',
            eligibility: 'Algumas universidades possuem acesso Campus-Wide, mas isso depende de contrato institucional; não há confirmação de licença do UniSales.',
            description: 'Suite estudantil para cálculo, análise de dados, simulação, engenharia e aprendizado com MATLAB e Simulink.',
            tags: ['MATLAB', 'Simulink', 'engenharia', 'dados'], officialUrl: 'https://www.mathworks.com/products/matlab/student.html',
            lastVerified: verifiedOn, status: 'verified', volatileFields: ['benefitLabel']
        }
    ];

    const sourceOverrides = {
        'github-copilot': ['github_student_pack', 'github_education'], mongodb: ['github_student_pack', 'github_education'],
        '1password-student': ['github_student_pack', 'github_education'], 'frontend-masters': ['github_student_pack', 'github_education'],
        notion: ['direct', 'institutional_email'], figma: ['direct', 'sheerid'], microsoft365: ['institution', 'institution_required'],
        spotify: ['direct', 'sheerid'], 'youtube-premium': ['direct', 'sheerid'], 'apple-education': ['direct', 'education_store'],
        'samsung-students': ['unidays', 'student_verification']
    };

    const logoOverrides = {
        github: 'logos/github.svg', 'github-copilot': 'logos/github-copilot.svg', jetbrains: 'logos/jetbrains.svg', notion: 'logos/notion.svg',
        figma: 'logos/figma.svg', miro: 'logos/miro.svg', autodesk: 'logos/autodesk.svg', mongodb: 'logos/mongodb.svg',
        spotify: 'logos/spotify.svg', 'apple-music': 'logos/apple-music.svg', 'youtube-premium': 'logos/youtube.svg',
        'samsung-students': 'logos/samsung.svg', 'apple-education': 'logos/apple.svg', '1password-student': 'logos/1password.svg',
        'lenovo-students': 'logos/lenovo.svg', 'dell-students': 'logos/dell.svg', 'unity-student': 'logos/unity.svg',
        'gitkraken-student': 'logos/gitkraken.svg', 'datacamp-student': 'logos/datacamp.svg',
        microsoft365: '../img-interno/MicrosoftT.png', 'microsoft-store-education': '../img-interno/MicrosoftT.png'
    };

    const fallbackLabels = {
        'frontend-masters': 'FM', 'unidays-brasil': 'U', isic: 'ISIC', 'tableau-students': 'T',
        'heroku-student': 'H', 'ableton-education': 'A', 'matlab-student': 'M'
    };

    const benefits = rawBenefits.map(benefit => {
        const [sourceChannel, accessMethod] = sourceOverrides[benefit.id] || [benefit.sourceChannel || 'direct', benefit.accessMethod || 'student_verification'];
        return Object.freeze({
            ...benefit,
            subcategory: benefit.subcategory || benefit.category,
            sourceChannel,
            accessMethod,
            logo: logoOverrides[benefit.id] || benefit.logo,
            fallbackLabel: benefit.fallbackLabel || fallbackLabels[benefit.id]
        });
    });

    const categories = [
        { id: 'development', label: 'Desenvolvimento', icon: 'code-2' },
        { id: 'productivity-studies', label: 'Produtividade & Estudos', icon: 'notebook-tabs' },
        { id: 'design-creativity', label: 'Design & Criatividade', icon: 'palette' },
        { id: 'cloud-data', label: 'Cloud & Dados', icon: 'cloud' },
        { id: 'education', label: 'Educação', icon: 'graduation-cap' },
        { id: 'technology', label: 'Tecnologia', icon: 'cpu' },
        { id: 'entertainment', label: 'Entretenimento', icon: 'play' },
        { id: 'shopping-benefits', label: 'Compras & Benefícios', icon: 'shopping-bag' },
        { id: 'rights-mobility', label: 'Direitos & Mobilidade', icon: 'ticket-check' }
    ];

    global.UniCheckBenefitsData = Object.freeze({
        benefits: Object.freeze(benefits),
        categories: Object.freeze(categories),
        verifiedOn
    });
})(window);
